# .travis.yml

language: python
python:
  - 3.7
  - 3.8
  - 3.9
cache: pip
dist: xenial
install:
  - pip install -r dev-requirements.txt
script:
  - make lint
  - make test
jobs:
  include:
    - stage: codecov
      name: "Upload coverage to codecov"
      script: codecov -t "$CODECOV_TOKEN" # submit coverage
      python: 3.7
